version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    ports:
      - "${DB_PORT}:5432"  # Map container port to host port

  app:
    build: .
    environment:
      DB_HOST: db  # Use service name to connect to Postgres
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      TOKEN_TTL: ${TOKEN_TTL}  
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_QRCODE_BUCKET: ${AWS_QRCODE_BUCKET}
    ports:
      - "8080:8080"  
    depends_on:
      - db  

volumes:
  postgres_data:  # Volume to persist database data