version: "3.8"

services:
  # Postgres service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    ports:
      - "${DB_PORT}:5432"  # Map container port to host port

  # Your application service
  app:
    build: .
    environment:
      DB_HOST: db  # Use service name to connect to Postgres
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      TOKEN_TTL: ${TOKEN_TTL}  # Load environment variables from .env file
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
    ports:
      - "8080:8080"  # Map container port to host port
    depends_on:
      - db  # Ensure Postgres starts before app

volumes:
  postgres_data:  # Volume to persist database data